[ISSUE #377]Translation for "数据集成-RocketMQ Connect 概览" Section in the v4.x & 5.0 Document (CN -> EN)
apache/rocketmq-site pull request #437
Opened 2023-01-12 15:14 UTC by mxsm

Please do not create a Pull Request without creating an issue first. 

## What is the purpose of the change

close #377 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [ ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2023-01-13 02:00 UTC, tsunghanjacktsai requested changes
Hey @mxsm , well done. Only some minor mistakes need to be fixed. Remember to correct them in the 5.0 version as well. Thx.

2023-01-13 02:00 UTC, tsunghanjacktsai commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/25RocketMQ Connect Overview.md
> +RocketMQ Connect is an important component of RocketMQ data integration, which can efficiently, reliably, and flowingly flow data in and out of RocketMQ from various systems. It is a separate, distri
> RocketMQ Connect is an important component of RocketMQ data integration, which can efficiently, reliably, and flowingly flow data in and out of RocketMQ from various systems.

RocketMQ Connect is an important component of RocketMQ data integration, which can transfer data in and out of RocketMQ from various systems efficiently and reliably.

2023-01-13 02:00 UTC, tsunghanjacktsai commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/25RocketMQ Connect Overview.md
> +In standalone mode, Connector tasks run on a single machine and Worker itself does not have high availability, task offset information is persisted locally. It is suitable for scenarios where there i
k8s -> K8s

2023-01-13 02:07 UTC, mxsm commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/25RocketMQ Connect Overview.md
> +In standalone mode, Connector tasks run on a single machine and Worker itself does not have high availability, task offset information is persisted locally. It is suitable for scenarios where there i
I will fix it later @tsunghanjacktsai

2023-01-13 14:28 UTC, mxsm commented
@tsunghanjacktsai  PTAL~

2023-01-16 02:18 UTC, tsunghanjacktsai approved these changes

2023-01-18 02:26 UTC, RongtongJin approved these changes

2023-01-18 02:26 UTC, merged