[ISSUE #378]Translation for "数据集成-概念" Section in the v4.x & 5.0 Document (CN -> EN)
apache/rocketmq-site pull request #438
Opened 2023-01-12 15:18 UTC by mxsm

Please do not create a Pull Request without creating an issue first. 

## What is the purpose of the change

close #378 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [ ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2023-01-14 12:02 UTC, Oliverwqcwrw requested changes

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/26RocketMQ Connect Concept.md
> +![RocketMQ基本模型](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-Concept.png)
The link seems is incorrect

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/26RocketMQ Connect Concept.md
> +![RocketMQ基本模型](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-process.png)
The link seems is incorrect

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/26RocketMQ Connect Concept.md
> +![RocketMQ基本模型](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/worker.png)
The link seems is incorrect

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/version-5.0/08-数据集成/26RocketMQ Connect Concept.md
>  ![RocketMQ基本模型](../picture/32rocketmq-connect/Connector-Task-Concept.png)
```suggestion
![RocketMQ Basic Model](../picture/32rocketmq-connect/Connector-Task-Concept.png)
```

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/version-5.0/08-数据集成/26RocketMQ Connect Concept.md
>  ![RocketMQ基本模型](../picture/32rocketmq-connect/Connector-Task-process.png)
```suggestion
![RocketMQ Basic Model](../picture/32rocketmq-connect/Connector-Task-process.png)
```

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/26RocketMQ Connect Concept.md
> +![RocketMQ基本模型](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-process.png)
```suggestion
![RocketMQ Basic Model](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-process.png)
```

2023-01-14 12:02 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/26RocketMQ Connect Concept.md
> +![RocketMQ基本模型](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-Concept.png)
```suggestion
![RocketMQ Basic Model](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-Concept.png)
```

2023-01-14 14:32 UTC, mxsm commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/26RocketMQ Connect Concept.md
> +![RocketMQ基本模型](E:/develop/github/contribution/rocketmq-site/i18n/en/docusaurus-plugin-content-docs/version-5.0/picture/32rocketmq-connect/Connector-Task-Concept.png)
my fault, i will fix it and re-submit later

2023-01-15 04:43 UTC, Oliverwqcwrw approved these changes

2023-01-18 02:28 UTC, RongtongJin approved these changes

2023-01-18 02:28 UTC, merged