[ISSUE #379]Translation for "数据集成-快速开始" Section in the v4.x & 5.0 Document (CN -> EN)
apache/rocketmq-site pull request #439
Opened 2023-01-12 15:23 UTC by mxsm

Please do not create a Pull Request without creating an issue first. 

## What is the purpose of the change

close #379 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [ ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2023-01-13 09:26 UTC, Oliverwqcwrw requested changes

2023-01-13 09:26 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/27RocketMQ Connect Quick Start.md
> +注：The configuration file instructions for the sample rocketmq-connect-sample are for reference only, different source/sink connectors have different configurations, please refer to the specific sourc
```suggestion
tips：The configuration file instructions for the sample rocketmq-connect-sample are for reference only, different source/sink connectors have different configurations, please refer to the specific source/sink connector.
```

2023-01-13 09:29 UTC, Oliverwqcwrw requested changes

2023-01-13 09:29 UTC, Oliverwqcwrw commented on i18n/en/docusaurus-plugin-content-docs/version-5.0/08-数据集成/27RocketMQ Connect Quick Start.md
> +注：The configuration file instructions for the sample rocketmq-connect-sample are for reference only, different source/sink connectors have different configurations, please refer to the specific sourc
```suggestion
tips：The configuration file instructions for the sample rocketmq-connect-sample are for reference only, different source/sink connectors have different configurations, please refer to the specific source/sink connector.
```

ditto

2023-01-13 09:52 UTC, mxsm commented on i18n/en/docusaurus-plugin-content-docs/current/08-数据集成/27RocketMQ Connect Quick Start.md
> +注：The configuration file instructions for the sample rocketmq-connect-sample are for reference only, different source/sink connectors have different configurations, please refer to the specific sourc
@Oliverwqcwrw  I will fix it and re-submit later

2023-01-14 11:53 UTC, Oliverwqcwrw approved these changes

2023-01-16 02:19 UTC, tsunghanjacktsai approved these changes

2023-01-16 03:11 UTC, merged